### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by luzpaz** [mfasano727/MBDynFCwb#3]
- [ ] Add some screenshots
- [x] Link to forum thread discussion
- [x] Add TODO/Roadmap section

**Comment by louisgag** [comment]
perhaps installation instructions as well...

**Comment by mfasano727** [comment]
Thanks @luzpaz  @louisgag 
I have a TODO list posted.  I have a link to instructions, and a link to the forum discusion.

I will put up screen shots when I have a shot worthy to post.

**Comment by luzpaz** [comment]
@mfasano727 do you mind if I give the README.md a cosmetic upgrade using some github markdown ?

**Comment by mfasano727** [comment]
@luzpaz 
Sure, Anything to improve the repository.  I guess I should be looking for a pull request.

Thanks,
